image: archlinux:latest
pages:
  script:
    - pacman -Syu zola cmake make ninja emscripten git
    - ./scripts/generate-graphics.sh
    - ./scripts/build-graphics.sh
  publish: public
  only:
    - main
